# -*- coding: utf-8 -*-
"""Copy of RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XVbLHAqhpdBuxhuMdsUtCdZXEi5mpsME
"""

!pip install -q langchain_openai faiss-cpu tiktoken langchain_community

import os
os.environ["OPENAI_API_KEY"] = "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"  # 🔐 Replace with your OpenAI API Key

from langchain_openai.embeddings import OpenAIEmbeddings
from langchain.vectorstores import FAISS
from langchain.text_splitter import CharacterTextSplitter
from langchain.document_loaders import TextLoader

#  Load sample document (replace with your own file)
with open("rag_context.txt", "w") as f:
    f.write("""Islamabad Real Estate Overview:

Zones:
1. Zone I – Core CDA sectors like F-6, F-7, G-9, etc. Fully developed.
2. Zone II – Sectors like G-15, G-16. Developing.
3. Zone III – Margalla Hills. Reserved for forests.
4. Zone IV – Private societies: Bahria Enclave, Park View City.
5. Zone V – DHA, Naval Anchorage, Soan Gardens.

CDA Sectors:
- F-6, F-7, F-8: PKR 15–25 Cr (Elite)
- G-10, G-11, G-13: PKR 6–14 Cr (Middle Class)
- I-8, I-9: PKR 8–18 Cr (Commercial/Mixed)
- D-12, E-11: PKR 6–15 Cr (Developing)

Private Societies:
- Bahria Town (Phases 1–8): PKR 1.5–4 Cr
- DHA Islamabad: PKR 2–7 Cr
- Gulberg Greens: PKR 3–6 Cr
- B-17: PKR 1.5–3.5 Cr
- Park View City: PKR 1.8–4 Cr

Price Trends (2020–2025):
- G-13: PKR 1.8 Cr → 3.2 Cr (+78%)
- D-12: PKR 3.5 Cr → 6 Cr (+71%)
- B-17: PKR 1 Cr → 2.8 Cr (+180%)
- DHA 2: PKR 2.5 Cr → 5.5 Cr (+120%)

CDA Approved Societies:
- ✅ Bahria Enclave
- ✅ Gulberg Greens
- ✅ OPF Housing
- ✅ Naval Anchorage
- ⏳ Park View City (under review)

Plot Size & Price Estimates:
- 5 Marla: F Sector 4–7 Cr, DHA 60–90 Lakh, Bahria 40–70 Lakh
- 10 Marla: F Sector 6–15 Cr, DHA 1.2–2 Cr, Bahria 70 Lakh–1.5 Cr
- 1 Kanal: F Sector 15–30 Cr, DHA 2–6 Cr, Bahria 1.5–3 Cr

Future Trends:
- AI for price prediction & fraud detection
- Tokenized land ownership via blockchain
- Smart cities expansion & digital property management
- Infrastructure and water access will greatly affect value""")
loader = TextLoader("rag_context.txt")
documents = loader.load()

#  Split text
text_splitter = CharacterTextSplitter(chunk_size=300, chunk_overlap=50)
docs = text_splitter.split_documents(documents)

#  Embeddings + FAISS Index
embedding = OpenAIEmbeddings()
db = FAISS.from_documents(docs, embedding)

from langchain.prompts import PromptTemplate

template = """
You are an AI assistant answering based on retrieved knowledge. Use the context to answer accurately.

Context:
{context}

Question:
{question}

Answer:"""

prompt = PromptTemplate(
    input_variables=["context", "question"],
    template=template,
)

from langchain.chains import RetrievalQA
from langchain.chat_models import ChatOpenAI

llm = ChatOpenAI(model_name="gpt-4o-mini", temperature=0)
qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type="stuff",
    retriever=db.as_retriever(),
    chain_type_kwargs={"prompt": prompt},
)

query = "Jinnah garden pros and cons?"
result = qa_chain.run(query)
print("💡 Answer:", result)

