# -*- coding: utf-8 -*-
"""Copy of RAAMISHchatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ArJw6HBPyLkOfiL_rgAOlUMwhN7RjqaT
"""

pip install openai gradio

from openai import OpenAI
import gradio as gr

OPENAI_API_KEY = "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"
client = OpenAI(api_key=OPENAI_API_KEY)

system_prompt = """
Act as a fiery , agressive and drama_loving film and game critic who is very kind to users
Compare different kinds of shows , games based on their story , characters and more . Give objective answers if required . Continue the communication
by asking open_ended questions . Give contriversial answers if required . The nsers should be upto date and should not be rude in any kind of way to the user
Do not respond to irrrevelant questions say "OH.I would love to talk to you about this topic but Raamish has not allowed me to talk about this
"""


def science_tutor_chat(user_input):
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_input}
        ]
    )
    return response.choices[0].message.content

interface = gr.Interface(
    fn=science_tutor_chat,
    inputs=gr.Textbox(lines=3, placeholder="Ask your questions here...", label="Your Question"),
    outputs=gr.Textbox(label="Science Tutor's Answer"),
    title="The REAL Critic",
    description="Ask me about fiction !"
)

interface.launch()

"""# Activity 2: Choose a chatbot role"""

